###[`sklearn.preprocessing`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing "sklearn.preprocessing").LabelEncoder
* _class_ sklearn.preprocessing.LabelEncoder[[source]](https://github.com/scikit-learn/scikit-learn/blob/ff1023fda/sklearn/preprocessing/_label.py#L36)[](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder "Permalink to this definition")
Encode target labels with value between 0 and n_classes-1.

This transformer should be used to encode target values,  _i.e._  `y`, and not the input  `X`.

Read more in the  [User Guide](https://scikit-learn.org/stable/modules/preprocessing_targets.html#preprocessing-targets).

In [1]:
from sklearn.preprocessing import LabelEncoder
items=[ 'TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서' ]

encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
print('인코딩 클래스:', encoder.classes_)


인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [3]:
print('디코딩 원본 값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### [`sklearn.preprocessing`](https://scikit-learn.org/1.1/modules/classes.html#module-sklearn.preprocessing "sklearn.preprocessing").OneHotEncoder
* _class_ sklearn.preprocessing.OneHotEncoder(_*_,  _categories='auto'_,  _drop=None_,  _sparse=True_,  _dtype=<class  'numpy.float64'>_,  _handle_unknown='error'_,  _min_frequency=None_,  _max_categories=None_)[[source]](https://github.com/scikit-learn/scikit-learn/blob/f3f51f9b6/sklearn/preprocessing/_encoders.py#L201)[](https://scikit-learn.org/1.1/modules/generated/sklearn.preprocessing.OneHotEncoder.html?highlight=onehot#sklearn.preprocessing.OneHotEncoder "Permalink to this definition")

In [26]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
X = np.array([["a"] * 5 + ["b"] * 20 + ["c"] * 10 + ["d"] * 3], dtype=object).T
ohe_1= OneHotEncoder(max_categories=3, sparse=False).fit(X)
print(ohe.infrequent_categories_,
ohe.transform([["a"], ["b"]]))


[array(['a', 'd'], dtype=object)] [[0. 0. 1.]
 [1. 0. 0.]]


C:\Users\yim\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [29]:
ohe_2= OneHotEncoder(max_categories=3, sparse_output=False, handle_unknown='ignore').fit(X)
ohe_2

OneHotEncoder(handle_unknown='ignore', max_categories=3, sparse_output=False)

In [9]:
X

array([['a'],
       ['a'],
       ['a'],
       ['a'],
       ['a'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['b'],
       ['c'],
       ['c'],
       ['c'],
       ['c'],
       ['c'],
       ['c'],
       ['c'],
       ['c'],
       ['c'],
       ['c'],
       ['d'],
       ['d'],
       ['d']], dtype=object)

In [31]:
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
labels=labels.reshape(-1,1)

oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)

print('원_핫 인코딩 데이터')
print(oh_labels.toarray())
print('원_핫 인코딩 데이터 차원')
print(oh_labels.shape)

원_핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원_핫 인코딩 데이터 차원
(8, 6)


In [32]:
from sklearn.preprocessing import LabelEncoder
items=np.array([ 'TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서' ])


encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)

labels=labels.reshapepe(-1,1)

oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)

print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


C:\Users\yim\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\yim\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
